#!/usr/bin/env python3
"""Generate prelude_embed.inc from the Skarn stdlib manifest.

Usage: gen_prelude_embed.py [--chunk <bytes>] <manifest> <std_dir> <output_inc>

Reads modules.manifest, finds each .skn file, and emits one
  { "prefix", R"delim(source)delim" },
entry per module into the output file.  The delimiter is chosen to
avoid any occurrence of  )delim"  inside the source.

--chunk <bytes> splits each module into adjacent raw-string literals of
about that size, cut at line ends; the compiler concatenates them into
one string.  MSVC needs it: it refuses a single string literal longer
than about 16 KB (error C2026).  CMakeLists.txt passes it only when the
compiler is MSVC, so for Clang and GCC the output is unchanged.
"""
import sys
import os


def safe_delimiter(source: str) -> str:
    """Return the shortest delimiter that does not appear in `source`."""
    delim = ""
    while True:
        if f"){delim}\"" not in source:
            return delim
        delim += "_"


def chunks(source: str, size: int) -> list:
    """`source` cut into pieces of about `size` bytes, each ending at a line end."""
    pieces = []
    current = ""
    for line in source.splitlines(keepends=True):
        current += line
        if len(current.encode("utf-8")) >= size:
            pieces.append(current)
            current = ""
    if current or not pieces:
        pieces.append(current)
    return pieces


def main() -> None:
    args = sys.argv[1:]
    chunk_size = 0
    if len(args) >= 2 and args[0] == "--chunk":
        chunk_size = int(args[1])
        args = args[2:]
    if len(args) != 3 or chunk_size < 0:
        print(f"usage: {sys.argv[0]} [--chunk <bytes>] <manifest> <std_dir> <output>",
              file=sys.stderr)
        sys.exit(1)

    manifest_path, std_dir, output_path = args[0], args[1], args[2]

    entries: list[tuple[str, str, str]] = []
    with open(manifest_path, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            if len(parts) < 2:
                continue
            prefix, filename = parts[0], parts[1]
            src_path = os.path.join(std_dir, filename)
            with open(src_path, encoding="utf-8") as sf:
                source = sf.read()
            entries.append((prefix, source, safe_delimiter(source)))

    with open(output_path, "w", encoding="utf-8", newline="\n") as out:
        out.write("// AUTO-GENERATED by gen_prelude_embed.py -- do not edit\n")
        for prefix, source, delim in entries:
            if chunk_size == 0:
                out.write(f'    {{ "{prefix}", R"{delim}({source}){delim}" }},\n')
            else:
                literals = "\n      ".join(f'R"{delim}({piece}){delim}"'
                                           for piece in chunks(source, chunk_size))
                out.write(f'    {{ "{prefix}", {literals} }},\n')


if __name__ == "__main__":
    main()
