#!/usr/bin/env python3
"""Generate prelude_embed.inc from the Skarn stdlib manifest.

Usage: gen_prelude_embed.py <manifest> <std_dir> <output_inc>

Reads modules.manifest, finds each .skn file, and emits one
  { "prefix", R"delim(source)delim" },
entry per module into the output file.  The delimiter is chosen to
avoid any occurrence of  )delim"  inside the source.
"""
import sys
import os


def safe_delimiter(source: str) -> str:
    """Return the shortest delimiter that does not appear in `source`."""
    delim = ""
    while True:
        if f"){delim}\"" not in source:
            return delim
        delim += "_"


def main() -> None:
    if len(sys.argv) != 4:
        print(f"usage: {sys.argv[0]} <manifest> <std_dir> <output>",
              file=sys.stderr)
        sys.exit(1)

    manifest_path, std_dir, output_path = sys.argv[1], sys.argv[2], sys.argv[3]

    entries: list[tuple[str, str, str]] = []
    with open(manifest_path, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            if len(parts) < 2:
                continue
            prefix, filename = parts[0], parts[1]
            src_path = os.path.join(std_dir, filename)
            with open(src_path, encoding="utf-8") as sf:
                source = sf.read()
            entries.append((prefix, source, safe_delimiter(source)))

    with open(output_path, "w", encoding="utf-8", newline="\n") as out:
        out.write("// AUTO-GENERATED by gen_prelude_embed.py -- do not edit\n")
        for prefix, source, delim in entries:
            out.write(f'    {{ "{prefix}", R"{delim}({source}){delim}" }},\n')


if __name__ == "__main__":
    main()
